logo overflow fixed
TheNinza/dsa-visualizer pull request #17
Opened 2022-10-06 10:47 UTC by ImAnshuJoshi

I have fixed the overflow of the image from the navbar . I have attached the pic below.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/101829944/194294179-42580405-932c-427d-81a7-c6655943e6e3.png">

2022-10-06 11:03 UTC, TheNinza requested changes

2022-10-06 11:03 UTC, TheNinza commented on src/components/navbar/navbar.jsx
> +                style={{ cursor: "pointer" ,height:'auto',maxHeight:'8vh'}}
use prettier to format the code. for example there are single quotes in the string instead of double quotes.

2022-10-06 11:03 UTC, TheNinza commented on src/components/navbar/navbar.styles.jsx
> +    height: "11vh",
Keep the height to 10 vh only to avoid extra scrolling on body.

2022-10-09 16:07 UTC, ImAnshuJoshi commented
<img width="960" alt="image" src="https://user-images.githubusercontent.com/101829944/194767271-81496217-5d91-4771-b6c5-d2e0dd5b8225.png">

@TheNinza i have tried to fix the logo overflowing using transform property .Its working better than before and havent disturbed the navabr height . Also i have formatted the code using prettier.

2022-10-09 18:30 UTC, TheNinza approved these changes

2022-10-09 18:31 UTC, TheNinza commented
Hey @ImAnshuJoshi,
This looks good. Merging

2022-10-09 18:32 UTC, merged